name: "Jim Thomas"
description: "The Personal Homepage for Jim Thomas"

url: "http://jimthomas.edu.com"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
